#!/bin/bash

USER_DIR="/home/safwan"

cd ${USER_DIR}

#update:
dnf -y update
#X-sever stuff:
dnf -y install @base-x #there is a package didnt match!!
#dnf -y install xorg-x11-server-Xorg xorg-x11-drv-{evdev,intel,synaptics} xorg-x11-xinit xterm terminus-fonts

#Build tools:
dnf -y install make automake gcc gcc-c++ kernel-devel

#git:
dnf -y install git

#Install display manager:

dnf install lightdm lightdm-gtk

#the default is multi-user
#use `systemctl set-default` to check
systemctl set-default graphical.target

#dwm required packages:

dnf -y install libX11-devel libXft-devel libXinerama-devel


#adding dwm to /user/share/xsesions

# cp ../xsessions/* /usr/share/xsessions # didnt work. Done manually




#install other pakcages

dnf -y install nitrogen vim polkit bash-completion \
    picom blueman terminator alacritty dunst dmenu \
    fontawesome-fonts arandr flameshot htop polkit-gnome \
    volumeicon pavucontrol rofi qt5ct numlockx udiskie \
    wget curl rust cargo redhat-mono-fonts lxappearance \
    materia-gtk-theme Thunar papirus-icon-theme network-manager-applet \


#$ sudo dnf install rust cargo

# needed by terminator
dnf -y install gsettings-desktop-schemas

#audio server
dnf -y install pipewire pipewire-utils
dnf -y install --allowerasing pipewire-pulseaudio
dnf -y install alsa-utils 


#compression tools

dnf -y install zip unzip tar util-linux-user bzip2


dnf -y install NetworkManager-bluetooth NetworkManager-wifi NetworkManager-wwan

#bluetooth
dnf -y install bluez blueman bluez-tools

echo "cloning the dotfiles repo"

cd ${USER_DIR} && git clone -b fedora https://github.com/SafwanElmadani/dotfiles.git


cd ${USER_DIR}/dotfiles && \

cp .xprofile ${USER_DIR}/ && \

mv ${USER_DIR}/.xprofile ${USER_DIR}/dwm-start && \

chmod +x ${USER_DIR}/dwm-start && \

cp -R .config/* ${USER_DIR}/.config && \

chmod -R +x ${USER_DIR}/.config/scripts


echo "Update the greeter session in /etc/lightdm/lightdm.conf to match greeter session name in /usr/share/xgreeters"
echo "cp safwan-dwm-buld/xsessions/* /usr/share/xsessions"


#Add change own later chown