#!/bin/bash

USER_DIR="/home/safwan"

#Install pfetch



cd ${USER_DIR} && git clone https://github.com/dylanaraps/pfetch.git && \
install pfetch/pfetch /usr/local/bin/


#fonts and emoji

dnf -y install google-noto-fonts-common
dnf -y install levien-inconsolata-fonts
dnf -y install gdouros-symbola-fonts


needed packages:
xorg-x11-util-macros
patch 

#for brightness
dnf install xbacklight

#bebugger
dnf install gdb

dnf install xinput


#twitter-twemoji-fonts// crashes dwm