#!/bin/bash

USER_DIR="/home/safwan"

#Install pfetch



cd ${USER_DIR} && git clone https://github.com/dylanaraps/pfetch.git && \
install pfetch/pfetch /usr/local/bin/


#fonts and emoji
#for dwm fonts install mononaki or Hack and change in the name in the config
#https://github.com/source-foundry/Hack
#https://github.com/madmalik/mononoki/blob/master/export/mononoki-Regular.ttf
#dont use the nerd font version because they add some icon for theier fonts.

dnf -y install google-noto-fonts-common
dnf -y install levien-inconsolata-fonts
dnf -y install gdouros-symbola-fonts

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# NEED TO INSTALL libXft-bgra first or dwm will crash
#install twitter emoji
dnf -y install twitter-twemoji-fonts
dnf -y install google-noto-emoji-color-fonts 

#install JoyPixels
wget https://cdn.joypixels.com/arch-linux/font/6.6.0/joypixels-android.ttf
cp joypixels-android.ttf JoyPixels.ttf
mkdir -p /home/safwan/.local/share/fonts/JoyPixels/
mv JoyPixels.ttf /home/safwan/.local/share/fonts/JoyPixels/

# then do: fc-cache -f -v 
# and fc-list | grep "Joy" to check if the system detect it.


#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$






#needed packages:
dnf -y install xorg-x11-util-macros patch
 
#for brightness
dnf install xbacklight

#bebugger
dnf install gdb

#input
dnf install xinput

#with zsh solves: _dnf_query_db:1: command not found: sqlite3
dnf install sqlite

#patch libXft:
# https://github.com/SafwanElmadani/libxft-bgra

#install emoji picker 
#sudo dnf install rofimoji
